planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["AStar", "GridBased"]
    AStar:
      plugin: "tb3_astar_planner/AStarPlanner"
      allow_unknown: false
      use_eight_connected: true
      tolerance: 0.35
      cost_penalty: 2.0
      max_iterations: 1000000
      lethal_cost: 253
    GridBased:
      plugin: "tb3_astar_planner/AStarPlanner"
      allow_unknown: false
      use_eight_connected: true
      tolerance: 0.35
      cost_penalty: 2.0
      max_iterations: 1000000
      lethal_cost: 253
